# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
title: Documentation
author: Broad Institute
copyright: "2024"
# logo: img/user-guide-u2os-fit-settings.png
logo: img/piximi-logo.svg

# Only build files that are in the ToC
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: false

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/piximi/documentation # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)
  path_to_book: piximi-documentation

html:
  favicon                   : "img/favicon.ico"  
  baseurl: documentation.piximi.app
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true  
  comments:
    hypothesis: true

parse:
  myst_enable_extensions:
    # Only required if you use html <img>
    - html_image
